# Generated by Django 5.0.7 on 2024-07-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=10)),
                ('userpw', models.CharField(max_length=15)),
                ('sessionid', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
